### PR TITLE
feat js package 

### PR DESCRIPTION
**Pull request by thomas-mauran**
The goal here is to create a js package to use the protofiles in the nest api

### CODE REVIEW

**Review by remi-espie — APPROVED** [review]
LGTM 👍

**Review by mmoreiradj — APPROVED** [review]

**Review by remi-espie — CHANGES_REQUESTED** [review]
Why use `camelCase` instead of `snake_case` for proto fields name ?
Proto official documentation says to do otherwise: https://protobuf.dev/programming-guides/style/#message-field-names...

**Comment by thomas-mauran** [comment]
> Why use `camelCase` instead of `snake_case` for proto fields name ? Proto official documentation says to do otherwise: https://protobuf.dev/programming-guides/style/#message-field-names...

```--ts_proto_opt=snakeToCamel=false``` => meaning we use snake_case instead of default camel

**Comment by remi-espie** [comment]
seems like i'm an idiot who can't read straight... My bad, LGTM :+1: !

**Review by remi-espie — APPROVED** [review]
LGTM :+1:

**Review by mfernd — APPROVED** [review]
Works for me :+1:

**Pull request merged**
